version: '3'
services:

 mysql:
   platform: linux/x86_64
   image: mysql:5.7
   container_name: express-mysql
   volumes:
    - "./.data/mysql:/var/lib/mysql"
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
   networks:
    - docker-networks-express

 phpmyadmin:
   depends_on:
    - mysql
   image: phpmyadmin/phpmyadmin
   container_name: express-phpmyadmin
   environment:
    - PMA_HOST=express-mysql
   restart: always
   ports:
    - "80:80"
   networks:
    - docker-networks-express

 dockerexpress:
   image: dockerexpress
   container_name: express-app
   build:
    context: app
    dockerfile: ./Dockerfile
   ports:
    - 3000:3000
   init: true
   volumes:
    - ./app:/usr/src/app
    - express-node-modules:/usr/src/app/node_modules
   networks:
    - docker-networks-express
  
networks:
 docker-networks-express:

volumes:
 express-node-modules:
